const express = require('express');
const router = express.Router();
const textController = require('../controllers/textController');

router.post('/capitalize-first-letter', textController.capitalizeFirstLetter);
router.post('/capitalize-words', textController.capitalizeWords);
router.post('/count-characters', textController.countOfChars);
router.post('/count-sentences', textController.countSentences);
router.post('/count-words', textController.countWords);
router.post('/extract-anagrams', textController.extractAnagrams);
router.post('/extract-biagrams-words', textController.extractWordBigrams);
router.post('/extract-capital-words', textController.capitalLetters);
router.post('/extract-common-word', textController.findMostCommonWordsFirst);
router.post('/extract-dates', textController.extractDates);
router.post('/extract-email-addresses', textController.extractEmails);
router.post('/extract-hashtags', textController.extractHashtags);
router.post('/extract-lowercase-words', textController.extractUniqueLowercaseWords);
router.post('/extract-numbers', textController.extractNumbers);
router.post('/extract-palindromes', textController.palindromeWords);
router.post('/extract-phone-numbers', textController.extractPhoneNumbers);
router.post('/extract-roman-numerals', textController.extractRomanNumerals);
router.post('/extract-times', textController.extractTimes);
router.post('/extract-trigrams', textController.extractTrigrams);
router.post('/extract-urls', textController.extractURLs);
router.post('/find-longest-word', textController.findLongestWord);
router.post('/find-rare-words', textController.findRareWords);
router.post('/find-shortest-word', textController.findShortestWord);
router.post('/remove-blanks', textController.removeBlanks);
router.post('/remove-duplicates', textController.removeDuplicateWords);
router.post('/remove-email-addresses', textController.removeEmailAddresses);
router.post('/remove-emojis', textController.removeEmojis);
router.post('/remove-hashtags', textController.removeHashtags);
router.post('/remove-html-entities', textController.RemoveHtmlEntitiesWrapper);
router.post('/remove-non-alphanumeric', textController.RemoveNonAlphanumericWrapper);
router.post('/remove-numbers', textController.removeNumbers);
router.post('/remove-phone-numbers', textController.removePhoneNumbers);
router.post('/remove-punctuation', textController.removePunctuation);
router.post('/remove-specific-words', textController.removeSpecificWords);
router.post('/remove-urls', textController.removeUrls);
router.post('/remove-whitespace', textController.removeWhitespace);
router.post('/remove-word-by-length', textController.removeWordsByLength);
router.post('/reverse-text', textController.reverseString);
router.post('/reverse-words-in-sentence', textController.reverseWordsInSentence);
router.post('/to-lowercase', textController.toLowercase);
router.post('/uppercase-text', textController.convertToUppercase);
router.post('/word-length-distribution', textController.wordLengthDistribution);

module.exports = router;
